### PR TITLE
Services Plans - M2M Table

### PR DESCRIPTION
**Pull request by udiptoKeel**

### CODE REVIEW

**Comment by MPratik-Keel** [comment]
@udiptoKeel - What is our intention behind creating **ServicesPlans** model??

**Comment by udiptoKeel** [comment]
@KeelTech  ANything pending here? Also, can u explain pratik's query?

**Comment by MPratik-Keel** [comment]
@udiptoKeel - Django creates this model internally for a many to many field, what is the purpose of defining this model explicitly here.

**Comment by KeelTech** [comment]
hey pratik,. planning for different prices for  services according top plans in future,...so customisation with this models can help!

**Review by KeelTech — APPROVED** [review]

**Pull request merged**
