### PR TITLE
jquery and views for crs calculator

### PR DESCRIPTION
**Pull request by phemmylintry**
I also fixed some merge conflict from the update of master done earlier today

### CODE REVIEW

**Comment by KeelTech** [comment]
can you remove the js file and local.py from this PR, because the js file is not gonna be apart of the django app...and local.py dont have any updates onlyy commented code

**Comment by phemmylintry** [comment]
@KeelTech please check

**Review by KeelTech — APPROVED** [review]

**Comment by KeelTech** [comment]
please put the info.log file to gitignore....

**Comment by phemmylintry** [comment]
> please put the info.log file to gitignore....

Okay

**Pull request merged**
